### ISSUE TITLE
Moco discontinued?

### ISSUE THREAD

**Issue by royteeuwen** [wttech/aem-stubs#58]
We use Moco as our testing framework for aem-stubs, but it seems this got deleted?

Could you give the reason for discontinueing? The benefit of moco is that it can live on another port, making so that you don't have to use context paths to specify the service and you just specify another hostname in your OSGi config

**Comment by krystian-panek-wttech** [comment]
To reduce maintenance effort.

If it is still used as you are reporting I will recover it soon ;) In WTT I haven't heard so far if sb used it, on GH too. You are the first one so sorry about that ;) 

I just need a few hours to upgrade the build and check dependencies and compatibility with the newer AEM. To do it well I need a week or two due to limited time for open source.

**Comment by krystian-panek-wttech** [comment]
here you go @royteeuwen https://github.com/wttech/aem-stubs/releases/tag/3.0.2

**Comment by royteeuwen** [comment]
Super 😄, thanks! sorry for the extra effort 🙈

**Comment by krystian-panek-wttech** [comment]
np :)
